### ISSUE TITLE
First Time Setup (invalid redirect URL)

### ISSUE THREAD

**Issue by Rasinzz** [Hexiro/spotify-to-musi#2]
I open the first time setup link, sign in, and I get directed to this URL giving me this error message `INVALID_CLIENT: Invalid redirect URL`. [Screenshot](https://i.imgur.com/PgVSgWq.png)

**Comment by Hexiro** [comment]
hmmmm im getting that too. I'll look into this and get back to you 👍🏼

**Comment by Rasinzz** [comment]
Hey, just re-set it up and now it's working for me. I don't know if it was just Spotify's servers or if I missed something in the setup process, but it's currently working for me.

**Comment by Hexiro** [comment]
okay! so i figured it out. In my example here i forgot the trailing / at the end of the url, but that is shown in the example screenshot and (more importantly) in the code and spotify doesn't like that missing /

![image](https://user-images.githubusercontent.com/42787085/166090750-af1ed64c-f7fa-49af-961a-f348422fe218.png)

**Comment by Rasinzz** [comment]
Actually, I add a `/` at the end of the redirect URL, that may have been what fixed it for me. Before I had it as `https://example.com/callback` but I changed it to `https://example.com/callback/`

**Comment by Hexiro** [comment]
yup that's what did it

**Comment by Rasinzz** [comment]
Said that same thing at the same time lol. Also, is there anyway I can transfer a specific playlist rather than all my Liked Songs?

**Comment by Hexiro** [comment]
I'm going to update the README and also make the instructions a bit more clear as I found they weren't as clear as I thought they were when I wrote them 4ish months ago

**Comment by Rasinzz** [comment]
Ok, if I find anything else that may be helpful I'll make a PR.

**Comment by Hexiro** [comment]
> Said that same thing at the same time lol. Also, is there anyway I can transfer a specific playlist rather than all my Liked Songs?

It should transfer all your playlists to separate musi playlists and liked songs to your musi library. Is it not doing that?

**Comment by Hexiro** [comment]
> Ok, if I find anything else that may be helpful I'll make a PR.

thank you for your help!

**Comment by Rasinzz** [comment]
> > Said that same thing at the same time lol. Also, is there anyway I can transfer a specific playlist rather than all my Liked Songs?
> 
> It should transfer all your playlists to separate musi playlists and liked songs to your musi library. Is it not doing that?

Oh, I wasn't able to complete it as I got an error. I'll have a look right now.

**Comment by Hexiro** [comment]
> > > Said that same thing at the same time lol. Also, is there anyway I can transfer a specific playlist rather than all my Liked Songs?
> > 
> > 
> > It should transfer all your playlists to separate musi playlists and liked songs to your musi library. Is it not doing that?
> 
> Oh, I wasn't able to complete it as I got an error. I'll have a look right now.

yeahhhhhh I'm gonna work on this project next time I get a chance (probably over the weekend, I didn't realize how bad it was). I'll let you know when all these pesky errors are ironed out. (I transferred my playlists a couple months ago and haven't really touched the code since)

**Comment by Rasinzz** [comment]
Alright no problem!
