### ISSUE TITLE
ValueError (too many values to unpack)

### ISSUE THREAD

**Issue by Rasinzz** [Hexiro/spotify-to-musi#3]
Screenshot of error:
![image](https://user-images.githubusercontent.com/42787085/166092824-60aa9a5b-c953-4542-81a9-5c999bfac557.png)

**Comment by Hexiro** [comment]
preciate it. could be that the video is less than a minute long or over an hour to where that code doesn't work. Regardless, I'll fix this next time I work on this (probably over the weekend)

**Comment by Rasinzz** [comment]
> preciate it. could be that the video is less than a minute long or over an hour to where that code doesn't work. Regardless, I'll fix this next time I work on this (probably over the weekend)

Alright

**Comment by Hexiro** [comment]
> > preciate it. could be that the video is less than a minute long or over an hour to where that code doesn't work. Regardless, I'll fix this next time I work on this (probably over the weekend)
> 
> Alright
@Rasinzz I cleaned some stuff up a little bit. Give it a shot and let me know how it goes! If you have any more issues feel free to comment them here or to open a new issue.

**Comment by Rasinzz** [comment]
> > > preciate it. could be that the video is less than a minute long or over an hour to where that code doesn't work. Regardless, I'll fix this next time I work on this (probably over the weekend)
> > 
> > 
> > Alright
> > @Rasinzz I cleaned some stuff up a little bit. Give it a shot and let me know how it goes! If you have any more issues feel free to comment them here or to open a new issue.

Ok, sounds good. I'm currently in the middle of something. Once I get a change I'll try it out and let you know how it goes!

**Comment by Hexiro** [comment]
No worries. Thank you for using my project!

**Comment by Rasinzz** [comment]
Ok, so I ran it and it was working flawlessly until the end... I got this error. It was around 96% complete when I last looked at it, so I'm not sure if it finished and then gave me the error, or if it give me the error right before it was complete. 

**FYI:** It did **_not_** print the Musi restore code.

![lTXjIly](https://user-images.githubusercontent.com/88259422/166120633-20389510-5a7e-4c07-8ed9-b9555a01e1f8.png)
.

**Comment by Hexiro** [comment]
damn. I'm not sure exactly why the name of the artist doesn't work for whatever song that is, if you wouldn't mind sending me your playlists I could maybe take a look and see if I can find it. Regardless, I'll push a fix that just skips the song if the artist name can't be found.

**Comment by Rasinzz** [comment]
> damn. I'm not sure exactly why the name of the artist doesn't work for whatever song that is, if you wouldn't mind sending me your playlists I could maybe take a look and see if I can find it. Regardless, I'll push a fix that just skips the song if the artist name can't be found.

Hey, I use the 'Local Files' setting to listen to some songs that are not on Spotify. For the local files option, it requires you to have the audio file on your local machine, so I assume the error is getting caused from a song from my local files (the file is probably poorly named or something. I'm going to make a new Spotify account and use the tool on a playlist that I know will 100% work and I'll get back to you.

**Comment by Hexiro** [comment]
> > damn. I'm not sure exactly why the name of the artist doesn't work for whatever song that is, if you wouldn't mind sending me your playlists I could maybe take a look and see if I can find it. Regardless, I'll push a fix that just skips the song if the artist name can't be found.
> 
> Hey, I use the 'Local Files' setting to listen to some songs that are not on Spotify. For the local files option, it requires you to have the audio file on your local machine, so I assume the error is getting caused from a song from my local files (the file is probably poorly named or something. I'm going to make a new Spotify account and use the tool on a playlist that I know will 100% work and I'll get back to you.

oooh yikes I've never messed around with that. Does that work cross devices? If so then Spotify has to be storing some kind of data on their servers, but I've always assumed that was 100% local and couldn't be fetched by the API.

**Comment by Rasinzz** [comment]
> > > damn. I'm not sure exactly why the name of the artist doesn't work for whatever song that is, if you wouldn't mind sending me your playlists I could maybe take a look and see if I can find it. Regardless, I'll push a fix that just skips the song if the artist name can't be found.
> > 
> > 
> > Hey, I use the 'Local Files' setting to listen to some songs that are not on Spotify. For the local files option, it requires you to have the audio file on your local machine, so I assume the error is getting caused from a song from my local files (the file is probably poorly named or something. I'm going to make a new Spotify account and use the tool on a playlist that I know will 100% work and I'll get back to you.
> 
> oooh yikes I've never messed around with that. Does that work cross devices? If so then Spotify has to be storing some kind of data on their servers, but I've always assumed that was 100% local and couldn't be fetched by the API.

No, it does not sync cross-devices. I just ran the tool on [this playlist](https://open.spotify.com/playlist/6sKKYKmGFXZU9Te0vwTpct?si=94a6dca6241e470c&pt=c16febd9f9975e75827fe8d8aed4b24a) and it worked perfectly!

**Comment by Rasinzz** [comment]
Since I have local files in certain playlists, I would recommend adding an option that allows someone to link a playlist and just convert that playlist, as a way to combat this.

**Comment by Hexiro** [comment]
> > > > damn. I'm not sure exactly why the name of the artist doesn't work for whatever song that is, if you wouldn't mind sending me your playlists I could maybe take a look and see if I can find it. Regardless, I'll push a fix that just skips the song if the artist name can't be found.
> > > 
> > > 
> > > Hey, I use the 'Local Files' setting to listen to some songs that are not on Spotify. For the local files option, it requires you to have the audio file on your local machine, so I assume the error is getting caused from a song from my local files (the file is probably poorly named or something. I'm going to make a new Spotify account and use the tool on a playlist that I know will 100% work and I'll get back to you.
> > 
> > 
> > oooh yikes I've never messed around with that. Does that work cross devices? If so then Spotify has to be storing some kind of data on their servers, but I've always assumed that was 100% local and couldn't be fetched by the API.
> 
> No, it does not sync cross-devices. I just ran the tool on [this playlist](https://open.spotify.com/playlist/6sKKYKmGFXZU9Te0vwTpct?si=94a6dca6241e470c&pt=c16febd9f9975e75827fe8d8aed4b24a) and it worked perfectly!

Nice! If you find a playlist it breaks on please let me know.

**Comment by Rasinzz** [comment]
> > > > > damn. I'm not sure exactly why the name of the artist doesn't work for whatever song that is, if you wouldn't mind sending me your playlists I could maybe take a look and see if I can find it. Regardless, I'll push a fix that just skips the song if the artist name can't be found.
> > > > 
> > > > 
> > > > Hey, I use the 'Local Files' setting to listen to some songs that are not on Spotify. For the local files option, it requires you to have the audio file on your local machine, so I assume the error is getting caused from a song from my local files (the file is probably poorly named or something. I'm going to make a new Spotify account and use the tool on a playlist that I know will 100% work and I'll get back to you.
> > > 
> > > 
> > > oooh yikes I've never messed around with that. Does that work cross devices? If so then Spotify has to be storing some kind of data on their servers, but I've always assumed that was 100% local and couldn't be fetched by the API.
> > 
> > 
> > No, it does not sync cross-devices. I just ran the tool on [this playlist](https://open.spotify.com/playlist/6sKKYKmGFXZU9Te0vwTpct?si=94a6dca6241e470c&pt=c16febd9f9975e75827fe8d8aed4b24a) and it worked perfectly!
> 
> Nice! If you find a playlist it breaks on please let me know.

I'll put together a playlist with a local file in it so it breaks, real quick. I'll link it when I'm done.

**Comment by Hexiro** [comment]
> Since I have local files in certain playlists, I would recommend adding an option that allows someone to link a playlist and just convert that playlist, as a way to combat this.

This is a great idea. I'll turn it into a CLI where you can pass a playlist and if you don't it just does the playlists / liked songs. Not sure how long this will take but I'll either start it later today or tomorrow probably

**Comment by Rasinzz** [comment]
> I'll put together a playlist with a local file in it so it breaks, real quick. I'll link it when I'm done.

Hey sorry for the wait, was out-n-about. Here's the link to the playlist: [playlist](https://open.spotify.com/playlist/1QObRX0bLkqb67dLN3VPXC?si=31823bacd657463f)

**Comment by Hexiro** [comment]
ty

**Comment by Rasinzz** [comment]
> ty

No problem. By the way, the songs that are greyed out are the ones that are local files.

**Comment by Rasinzz** [comment]
Ok, so it's able to find the local file songs, _if they are named correctly_. I guess the reason why I got the error is because some of songs were named poorly (for example, some were just named something random without any relation to the song itself... no artist name or song name)

**Comment by Hexiro** [comment]
Do you think I should just skip local files, or should I search YouTube with the name of the local file? It's more likely to raise a false positive, but it's probably more convenient.

**Comment by Hexiro** [comment]
For now i'm just going to skip local files because it's easier, but i'll rethink this in the future

**Comment by Rasinzz** [comment]
> Do you think I should just skip local files, or should I search YouTube with the name of the local file? It's more likely to raise a false positive, but it's probably more convenient.

I would say allow users the option to choose if it does or does not search local files, but have it search local files by default.

**Comment by Hexiro** [comment]
hopefully most common issues should be fixed for now. I'll revisit this tomorrow and see how I can transform it to a CLI :)

**Comment by Rasinzz** [comment]
> hopefully most common issues should be fixed for now. I'll revisit this tomorrow and see how I can transform it to a CLI :)

Ok, great! I'll look into it also

**Comment by Hexiro** [comment]
> > hopefully most common issues should be fixed for now. I'll revisit this tomorrow and see how I can transform it to a CLI :)
> 
> Ok, great! I'll look into it also

cli is in a good spot rn. don't think you can install it yet because I didn't finish the install script but you could run it locally with `python -m spotify_to_musi` inside the `spotify-to-musi` (note: dashes) directory if you'd like to try it out.

https://github.com/Hexiro/spotify-to-musi/tree/cli

**Comment by Hexiro** [comment]
i also still need to include the functionality that makes it so you can select a playlist

**Comment by Rasinzz** [comment]
> > > hopefully most common issues should be fixed for now. I'll revisit this tomorrow and see how I can transform it to a CLI :)
> > 
> > 
> > Ok, great! I'll look into it also
> 
> cli is in a good spot rn. don't think you can install it yet because I didn't finish the install script but you could run it locally with `python -m spotify_to_musi` inside the `spotify-to-musi` (note: dashes) directory if you'd like to try it out.
> 
> https://github.com/Hexiro/spotify-to-musi/tree/cli

Looking good

**Comment by Hexiro** [comment]
closing as i believe this was resolved
