### ISSUE TITLE
--playlist Error

### ISSUE THREAD

**Issue by Rasinzz** [Hexiro/spotify-to-musi#4]
Got an error when trying to use the `--playlist` command.

This is the command I ran: `python -m spotify_to_musi transfer --playlist https://open.spotify.com/playlist/4Sn3ZXM6ULcZ7uG1dXS4gE?si=b0580e45551a4e23`

This is the error I got: ![Error Image](https://i.imgur.com/6Q9H8It.png)

**Comment by Hexiro** [comment]
thank you for reporting! I'll look into this

**Comment by Hexiro** [comment]
not sure why it's null. I just pushed a fix that will skip the song if it is.

**Comment by Hexiro** [comment]
p.s. you should be able to run `python -m pip install git+https://github.com/Hexiro/spotify-to-musi@cli` to install it and then use `spotify-to-musi` or `spotify_to_musi` in cmd.

**Comment by Rasinzz** [comment]
> not sure why it's null. I just pushed a fix that will skip the song if it is.

Ok I'll test it when I get home

**Comment by Rasinzz** [comment]
> p.s. you should be able to run `python -m pip install git+https://github.com/Hexiro/spotify-to-musi@cli` to install it and then use `spotify-to-musi` or `spotify_to_musi` in cmd.

Very nice!

**Comment by Hexiro** [comment]
sounds good 👍🏼

**Comment by Rasinzz** [comment]
> > not sure why it's null. I just pushed a fix that will skip the song if it is.
> 
> Ok I'll test it when I get home

Worked great!

https://i.imgur.com/4xrpdKW.png

**Comment by Rasinzz** [comment]
> > > not sure why it's null. I just pushed a fix that will skip the song if it is.
> > 
> > 
> > Ok I'll test it when I get home
> 
> Worked great!
> 
> [Screenshot](https://i.imgur.com/4xrpdKW.png)

**Comment by Hexiro** [comment]
lets goooo! Let me know if you have any more suggestions or find any more bugs 😁
